### ISSUE TITLE
[Compatibility] RimHud hides Pokémon level in bottom left menu when Pokémon is selected

### ISSUE THREAD

**Issue by Gargamiel** [Gargamiel/PokeWorld#3]

**Comment by Bbansjkl** [comment]
You can fix that by opening RimHud's config and adding the stat "Level".

![grafik](https://user-images.githubusercontent.com/39167840/141673002-b1df35f3-e4fe-41a5-bb73-ecc743309863.png)

**Comment by Gargamiel** [comment]
commit b25a25e7575d319eb296aea1b4f93bf604699a1e fixed the issue by adding level, experience and happiness in the inspect pane text
