### ISSUE TITLE
Resurrector Serum breaks the game when administered to a Pokémon

### ISSUE THREAD

**Issue by Gargamiel** [Gargamiel/PokeWorld#4]

**Comment by NRFBToyStore** [comment]
Just tested using the DEV command to "resurrect" and it nuked the game/UI. I would post code but my log like is a GIG long, due to the PW_Legendary error happening 800 times a second.

**Comment by Gargamiel** [comment]
It may probably be due to the way the mod handle Pokémon feature (CompPokemon & subcomponents) after their death. I believe the mod simply destroys the data and the game cant find them again if the Pokémon is resurrected.

**Comment by Gargamiel** [comment]
Fixed, it was indeed a problem of setting stuff to null after death when i shouldn't have
